# Generated by Django 2.2.9 on 2020-01-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200110_1907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
